Repository sendgrid/sendgrid-nodejs, pull requests merged in 2018-06, with the labels that each got.

#691 Added support for dynamicTemplateData
  package.json
  packages/client/yarn.lock
  packages/helpers/classes/mail.js
  packages/helpers/classes/mail.spec.js
  packages/helpers/classes/personalization.d.ts
  packages/helpers/classes/personalization.js
  packages/helpers/classes/personalization_specs/PERSONALIZATION-SPECS-README.md
  packages/helpers/classes/personalization_specs/reverse-merge-dynamic_teplate_data.spec.js
  packages/helpers/classes/personalization_specs/set_dynamic_template_data.spec.js
  packages/helpers/classes/personalization_specs/to-json.spec.js
  packages/helpers/helpers/merge-data-deep.d.ts
  packages/helpers/helpers/merge-data-deep.js
  packages/helpers/helpers/merge-data-deep.spec.js
  packages/helpers/index.d.ts
  packages/helpers/package.json
  packages/helpers/yarn.lock
  yarn.lock
Labels: status: code review request

#666 Bumped the moment, chai-as-promised, and dirty-chai version in package.json
  package-lock.json
  package.json
Labels: difficulty: easy, status: code review request, type: community enhancement

#651 Change `contentId` to `content_id`
  packages/mail/USE_CASES.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#628 Repository overview sendgrid
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#603 Add links to CONTRIBUTING.MD
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#610 Exclude esdoc node modules
  .esdoc.json
Labels: difficulty: easy, status: code review request, type: bug
