Repository sendgrid/sendgrid-nodejs, pull requests merged in 2018-08, with the labels that each got.

#720 updated readme tags
  README.md
Labels: difficulty: easy, status: code review request, type: docs update

#726 Readability update
  CONTRIBUTING.md
Labels: status: ready for deploy, type: docs update

#728 Added link to docs from README #679
  README.md
Labels: status: code review request

#490 Added how to deploy simple hello world app on Azure
  packages/client/USE_CASES.md
  packages/mail/USE_CASES.md
Labels: difficulty: medium, hacktoberfest, status: ready for deploy, type: docs update
