Repository sendgrid/sendgrid-nodejs, pull requests merged in 2018-10, with the labels that each got.

#749 Update docs to show an example on how to enable tracking settings.
  packages/mail/USE_CASES.md
Labels: difficulty: easy, status: code review request, type: community enhancement

#754 Fix subscription-widget node engine version
  packages/subscription-widget/package.json
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#757 Upgrade request to 2.88.0 (latest) to address issue #661
  packages/client/package.json
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: security

#716 MailData must have dynamicTemplateData property
  packages/helpers/classes/mail.d.ts
Labels: difficulty: medium, status: code review request, type: community enhancement

#751 Update README.md to include the CLA
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#759 Add documentation for Email Activity API
  packages/client/USAGE.md
  packages/client/USE_CASES.md
  use-cases/README.md
  use-cases/email-activity.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#792 Add inbound parse webhook example
  examples/inbound-parse-docker/.dockerignore
  examples/inbound-parse-docker/.gitignore
  examples/inbound-parse-docker/CONTRIBUTING.md
  examples/inbound-parse-docker/Dockerfile
  examples/inbound-parse-docker/LICENSE
  examples/inbound-parse-docker/README.md
  examples/inbound-parse-docker/app.js
  examples/inbound-parse-docker/docker-compose.debug.yml
  examples/inbound-parse-docker/docker-compose.yml
  examples/inbound-parse-docker/example-webhook-payload.txt
  examples/inbound-parse-docker/k8s/inbound-parse.yml
  examples/inbound-parse-docker/package-lock.json
  examples/inbound-parse-docker/package.json
Labels: difficulty: very hard, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#795 Add first-timers.md file for newcomers
  first-timers.md
  static/img/github-fork.png
  static/img/github-sign-up.png
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#763 [inbound-mail-parser] fix(deps): Update mailparser to 2.3.4
  packages/inbound-mail-parser/package.json
  packages/inbound-mail-parser/yarn.lock
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#773 kubernetes secrets "\n" problem FIX.
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#802 Update OSI code of conduct link
  CODE_OF_CONDUCT.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#793 Warn if dynamic template contains non-escaped character
  packages/helpers/classes/mail.js
  packages/helpers/classes/mail.spec.js
  packages/helpers/constants/index.js
  use-cases/transactional-templates.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#789 Correct link for environment variables setup
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#785 #765 - Updating the troubleshooting.md
  TROUBLESHOOTING.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#784 docs: specify custom arguments must have string values
  use-cases/customization.md
  use-cases/kitchen-sink.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#780 v3 send email broken link fixed in TROUBLESHOOTING.md
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#779 Contributing.md broken links fix
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#774 Run *.md Documents Through Grammerly & Update Accordingly
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  packages/client/README.md
  packages/client/USAGE.md
  packages/client/USE_CASES.md
  packages/helpers/README.md
  packages/inbound-mail-parser/README.md
  packages/mail/README.md
  packages/mail/USE_CASES.md
  packages/subscription-widget/README.md
  use-cases/cc-bcc-reply-to.md
  use-cases/single-email-multiple-recipients.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#770 [contact-importer] Update to support @sendgrid/client v6.X
  packages/contact-importer/README.md
  packages/contact-importer/package.json
  packages/contact-importer/src/importer.js
  packages/contact-importer/src/importer.spec.js
  packages/contact-importer/yarn.lock
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#767 Add conformance to style standards
  .eslintignore
  .eslintrc.yaml
  .travis.yml
  CONTRIBUTING.md
  package.json
  packages/inbound-mail-parser/src/parser.spec.js
  packages/mail/src/classes/mail-service.js
  packages/subscription-widget/server/controllers/contact_list_controller.js
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#645 Clarified how you can change the sender name
  packages/mail/USE_CASES.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#586 Added the lines to .travis.yml as requested
  .travis.yml
Labels: difficulty: easy, status: ready for deploy, type: sendgrid enhancement

#585 updated usage for /categories/stats
  packages/client/USAGE.md
Labels: difficulty: medium, status: ready for deploy, type: community enhancement

#583 Fix readme instructions and replace stray tab indentation by spaces
  packages/client/README.md
  packages/helpers/classes/attachment.js
Labels: difficulty: easy, status: ready for deploy, type: community enhancement

#525 Add statistics helper class
  packages/helpers/classes/index.js
  packages/helpers/classes/statistics.d.ts
  packages/helpers/classes/statistics.js
  packages/helpers/classes/statistics.spec.js
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#522 Comma bug in name #448
  packages/helpers/classes/email-address.js
  packages/helpers/classes/email-address.spec.js
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#502 Prevent secrets from sending in email
  packages/mail/src/classes/mail-service.js
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#488 Add example use case for Slack event integration.
  packages/mail/USE_CASES.md
Labels: difficulty: medium, status: ready for deploy, type: docs update

#826 Fixed capitalization for "SendGrid" in **Contact the Moderators**
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#819 Fix typo in USE_CASES.md
  packages/mail/USE_CASES.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#809 Properly capitalize "SendGrid" brand
  .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
  packages/client/src/classes/client.js
  packages/contact-importer/src/importer.js
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#804 Event webhook docker
  examples/webhooks-docker/.dockerignore
  examples/webhooks-docker/.gitignore
  examples/webhooks-docker/CONTRIBUTING.md
  examples/webhooks-docker/Dockerfile
  examples/webhooks-docker/LICENSE
  examples/webhooks-docker/README.md
  examples/webhooks-docker/app.js
  examples/webhooks-docker/docker-compose.debug.yml
  examples/webhooks-docker/docker-compose.yml
  examples/webhooks-docker/example-email-parse-payload.txt
  examples/webhooks-docker/example-event-notification.txt
  examples/webhooks-docker/k8s/inbound-parse.yml
  examples/webhooks-docker/package-lock.json
  examples/webhooks-docker/package.json
  examples/webhooks-docker/routes/events.js
  examples/webhooks-docker/routes/inbound-parse.js
Labels: difficulty: very hard, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#824 Fix Travis CI build failures on master
  .travis.yml
  packages/mail/src/classes/mail-service.js
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#798 Update transactional-templates.md
  use-cases/transactional-templates.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement
