Repository sendgrid/sendgrid-nodejs, pull requests merged in 2019-05, with the labels that each got.

#925 Twilio Branding and SMS update
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  examples/webhooks-docker/CONTRIBUTING.md
  examples/webhooks-docker/LICENSE
  examples/webhooks-docker/README.md
  examples/webhooks-docker/app.js
  examples/webhooks-docker/package.json
  first-timers.md
  package.json
  packages/client/README.md
  packages/client/USAGE.md
  packages/client/USE_CASES.md
  packages/client/package.json
  packages/client/src/classes/client.js
  packages/contact-importer/README.md
  packages/contact-importer/package.json
  packages/contact-importer/src/importer.js
  packages/contact-importer/src/importer.spec.js
  packages/helpers/README.md
  packages/helpers/package.json
  packages/inbound-mail-parser/README.md
  packages/inbound-mail-parser/package.json
  packages/inbound-mail-parser/src/parser.js
  packages/inbound-mail-parser/src/parser.spec.js
  packages/mail/README.md
  packages/mail/USE_CASES.md
  packages/mail/package.json
  packages/subscription-widget/README.md
  packages/subscription-widget/app.json
  use-cases/README.md
  use-cases/domain-white-label.md
  use-cases/email-stats.md
  use-cases/sms.md
Labels: difficulty: medium, status: code review request, status: ready for deploy, type: docs update

#908 fix #906: Move @types dependencies to devDependencies for client
  packages/client/package.json
Labels: status: code review request

#932 Allows hiding warnings
  packages/helpers/classes/mail.d.ts
  packages/helpers/classes/mail.js
  use-cases/README.md
  use-cases/hide-warnings.md
Labels: difficulty: medium, status: ready for deploy, type: community enhancement

#923 Fix a broken link in docs
  packages/inbound-mail-parser/README.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#898 Added setTimeout method to the MailService class
  packages/mail/src/classes/mail-service.js
  use-cases/README.md
  use-cases/timeout.md
Labels: difficulty: medium, status: code review request, status: ready for deploy
