Repository sendgrid/sendgrid-nodejs, pull requests merged in 2019-06, with the labels that each got.

#935 Fixed deepmerge module export naming issue
  packages/helpers/classes/personalization.js
Labels: difficulty: easy, status: code review request, type: community enhancement

#939 Fix personalizations dynamic bug
  packages/helpers/classes/mail.js
  packages/helpers/classes/personalization.d.ts
  test/typescript/helpers.ts
Labels: difficulty: medium, status: code review request, type: bug

#943 Update url in "DYNAMIC_TEMPLATE_CHAR_WARNING" to point to a working current link
  packages/helpers/constants/index.js
Labels: difficulty: easy, status: ready for deploy, type: bug, type: docs update

#900 Return promise with catch handler if callback provided
  packages/client/src/classes/client.js
Labels: status: code review request
