Repository sendgrid/sendgrid-nodejs, pull requests merged in 2020-02, with the labels that each got.

#984 docs: fix typo 'Feild' to 'Field'
  use-cases/kitchen-sink.md
Labels: status: code review request

#921 fix: update MailService constructor property definition in TypeScript declaration
  packages/mail/src/mail.d.ts
Labels: status: code review request

#1039 fix: upgrade deepmerge to resolve webpack import issue
  packages/helpers/package.json
  packages/helpers/yarn.lock
Labels: status: code review request

#1040 fix: update Client constructor property definition in TS declaration
  packages/client/src/client.d.ts
Labels: status: code review request

#878 docs: Update USAGE.md to prevent query double encoding
  packages/client/USAGE.md
Labels: status: code review request

#989 docs: Update README.md to explicitly state that 'send()' returns a promise
  packages/mail/README.md
Labels: status: code review request

#877 docs: Improve the mail package's README to handle the async send()
  packages/mail/README.md
Labels: status: code review request

#825 docs: Properly capitalize Brands
  .github/PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  examples/webhooks-docker/CONTRIBUTING.md
  packages/client/README.md
  packages/helpers/README.md
  packages/inbound-mail-parser/README.md
  packages/mail/README.md
  packages/subscription-widget/README.md
  use-cases/transactional-templates.md
Labels: difficulty: easy, hacktoberfest, status: code review request

#827 docs: Fix grammatical errors in README
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: community enhancement

#1041 fix: require in TS at least 1 type of content for sending mail
  packages/mail/src/mail.d.ts
Labels: status: code review request
