Repository sendgrid/sendgrid-nodejs, pull requests merged in 2020-10, with the labels that each got.

#1203 chore: remove chalk dependency
  packages/helpers/classes/response-error.js
  packages/helpers/package.json
Labels: status: code review request

#1208 docs: Add eventwebhook package to main README
  README.md
Labels: status: code review request

#771 feat: Extend client.setDefault[Request,Headers] to accept objects
  packages/client/README.md
  packages/client/src/classes/client.js
  packages/client/src/client.d.ts
  test/typescript/client.ts
Labels: difficulty: medium, status: code review request

#712 feat: Add method chaining in mail-service.js
  packages/mail/src/classes/mail-service.js
Labels: difficulty: easy, status: code review request
